name: Containerize the react application and deploy it onto EC2 

on:
  push:
    branches: [main]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: "This is a dummy step"
        run: echo "Testing"
