name: Containerize the react application and deploy it onto EC2

on:
  push:
    branches: [main]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source..
        uses: actions/checkout@v4

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_User}} -p ${{secrets.DOCKER_PASSWORD}} docker.io

      - name: Build docker image
        run: docker build -t billumi/shoppingcart-frontend .

      - name: Publish image to docker hub
        run: docker push billumi/shoppingcart-frontend:latest

  deploy:
    needs: docker-build
    runs-on: [aws-ec2-for-shoppingcart-fe]
    steps:
      - name: pull image from docker hub
        run: echo "pulling image from docker hub"
       
